name: BananoChests
version: '${project.version}'
main: miner82.bananochests.BananoChestsMain
api-version: 1.19
authors: [Miner82]
description: A lockable chests plugin
commands:
  reloadbananochestsconfig:
    description: Used to reload the configuration at runtime.
    aliases: [bcreloadcfg]
    permission: reloadconfig
    permission-message: You do not have permission to use this command!
  securechest:
    description: Used to lock/unlock/share/view the status of the targeted storage block.
    aliases: [sc, chest, barrel, shulker]
    permission: securechest
    permission-message: You do not have permission to use this command!